//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBiblioteka.WinUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBiblioteka.WinUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap blacklogo {
            get {
                object obj = ResourceManager.GetObject("blacklogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clanavatar {
            get {
                object obj = ResourceManager.GetObject("clanavatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalno 4 karaktera..
        /// </summary>
        public static string DuzinaFormat {
            get {
                return ResourceManager.GetString("DuzinaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan format. Godina mora sadržavati 4 broja!.
        /// </summary>
        public static string GodinaNeispravanFormat {
            get {
                return ResourceManager.GetString("GodinaNeispravanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan format. Prvo slovo mora biti veliko, minimalno 3 i maximalno 20 karaktera..
        /// </summary>
        public static string ImeNeispravanFormat {
            get {
                return ResourceManager.GetString("ImeNeispravanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventarni broj mora sadržavati od 6 do 9 brojeva!.
        /// </summary>
        public static string InventarniBrojFormat {
            get {
                return ResourceManager.GetString("InventarniBrojFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iznos uplate mora biti veći od 0 KM..
        /// </summary>
        public static string IznosUplate {
            get {
                return ResourceManager.GetString("IznosUplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinke se ne podudaraju!.
        /// </summary>
        public static string LozinkaFail {
            get {
                return ResourceManager.GetString("LozinkaFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prvo slovo mora biti veliko, minimalno 3 i maximalno 30 karaktera..
        /// </summary>
        public static string NazivNeispravanFormat {
            get {
                return ResourceManager.GetString("NazivNeispravanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalno 3 karaktera, a maksimalno 20..
        /// </summary>
        public static string NazivNeispravnaDuzina {
            get {
                return ResourceManager.GetString("NazivNeispravnaDuzina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan format!.
        /// </summary>
        public static string NeispravanFormat {
            get {
                return ResourceManager.GetString("NeispravanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno polje!.
        /// </summary>
        public static string ObaveznoPolje {
            get {
                return ResourceManager.GetString("ObaveznoPolje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan format. Primjer: 060-000-000 ili 060/000/0000 ili 0621234567.
        /// </summary>
        public static string TelefonNeispravanFormat {
            get {
                return ResourceManager.GetString("TelefonNeispravanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate označiti barem jednu ulogu za uposlenika !.
        /// </summary>
        public static string UlogeFormat {
            get {
                return ResourceManager.GetString("UlogeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap uposlenikavatar {
            get {
                object obj = ResourceManager.GetObject("uposlenikavatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap whitelogo {
            get {
                object obj = ResourceManager.GetObject("whitelogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
